### ISSUE TITLE
400 bad request on PUT requests with DataCiteXML

### ISSUE THREAD

**Issue by pameyer** [datacite/cheetoh#5]
Switched to https://submit.test.datacite.org (as recommended in #3 ). Unable to get auth failures on GET requests within valid credentials; on PUT request was able to get an auth failure and extract realm.

Still getting 400 errors on PUT requests with XML that worked interactively. Tried several endpoints in case I was using an incorrect one (https://submit.test.datacite.org/id/%s , https://ez.test.datacite.org/id/%s), same behavior.

Docs (https://support.datacite.org/v1.1/reference#create-doi) suggest that the DOI needs to have / in the identifier escaped - @mfenner can you clarify this?

These attempts are with escaped DataCite XML in ANLV `datacite` element, if that's relevant.

**Comment by pameyer** [comment]
@mfenner anything I can do from my end to help out with this?

**Comment by mfenner** [comment]
@pameyer no need to escape the identifier. The DataCite XML needs to be escaped for ANVL. Can you paste what you are depositing, or send via email?

**Comment by pameyer** [comment]
@mfenner I emailed the request body (DataCite XML with ANVL escaping).

**Comment by mfenner** [comment]
I get a `422` status when trying to reproduce your request (what you sent by email). Will do further investigation and let you know.

**Comment by mfenner** [comment]
@pameyer there was a bug in the ANVL parsing library I wrote earlier this month, not handling escaping of `:` properly. This is fixed and a new version deployed, and your request body now works for DOI registration

**Comment by pameyer** [comment]
@mfenner Thanks!

I'm still seeing `400` errors; but if you were seeing `422` instead I suspect there's something additional going on.  I'll do some more troubleshooting and let you know what I find out.

**Comment by mfenner** [comment]
Sorry, the 422 is only internally from upstream APIs, you should only see 400. I can check additional examples if that helps.

**Comment by pameyer** [comment]
@mfenner The second problem turned out to be user error.  More specifically, I was trying to create an already-created identifier; which was (correctly) returning an error.  When I change this, everything looks good from my end.

Thanks again!

**Comment by mfenner** [comment]
Great!
